spring:
  application:
    name: bootcamp-service
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: xxxxx
name:
  firstName: Maulana
  lastName: Daffa

server:
  port: 3000
