spring:
  application:
    name: bootcamp-service
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: xxxxxx
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
    show-sql: true
    generate-ddl: true

name:
  firstName: Maulana
  lastName: Daffa

header:
  request:
#    api-key: ecd7d484-1bdf-4f71-8c41-543c4d0ef05e
    api-key: ${API_KEY}

server:
  port: 3000